version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: registration_login
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
