version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo_db
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
